### ISSUE TITLE
Cannot run gist containing more than two files

### ISSUE THREAD

**Issue by poxip** [Xion/gisht#2]
If gist contains more than just one file, like [this](https://gist.github.com/poxip/60624993f44edcae6b56), you can __only__ (sic!) run that first one, or the second.
```
michal@michal-E1-571G:~$ gisht poxip/file2.py
WARNING: gisht is used to download & run code from a remote source.

Never run gists that you haven't authored, and/or do not trust.
Doing so is dangerous, and may expose your system to security risks!

(If you continue, this warning won't be shown again).

Do you want to continue? [y/N]: y
file2.py
michal@michal-E1-571G:~$ gisht poxip/file1.py
cloning repository for gist poxip/file1.py failed (exitcode 128)
fatal: destination path '/home/michal/.gisht/gists/60624993f44edcae6b56' already exists and is not an empty directory.
```
As you see, gist's directory comes from __gist's hash__, but every file in gist has its own unique id, that can be used to avoid situations like above.
```json
{  
  "files":{  
     "file1.py":{  
        "filename":"file1.py",
        "type":"application/x-python",
        "language":"Python",
        "raw_url":"https://gist.githubusercontent.com/poxip/60624993f44edcae6b56/raw/2b7cb579aaeff09c0f695288572398a94da15df4/file1.py",
        "size":39
     },
     "file2.py":{  
        "filename":"file2.py",
        "type":"application/x-python",
        "language":"Python",
        "raw_url":"https://gist.githubusercontent.com/poxip/60624993f44edcae6b56/raw/24bcb84698b99cb3a863c01fed19a20ca3cc1992/file2.py",
        "size":39
     }
  }
}
```

**Comment by Xion** [comment]
I'm skeptical if this case is worth supporting. Gists are meant to be rather self-contained, and they rarely go beyond a single file anyway. (Indeed, GitHub is quite unique among pastebin-like sites to even support that).

Error messaging could be better, though. In your example, gist `poxip/file2.py` essentially does not exist, so the program should say as much.

**Comment by Xion** [comment]
Okay, after further research I determined GitHub was rather fragile way of assigning names to gists. Namely, the first file in the alphabetical order becomes the gist name, and it may change if files are added or removed. Bad GitHub, bad :(

There is no way to avoid all problems this entails, but we can detect them and warn the user when they occur, preventing the situations that can be only fixed manually in the data directory.
